require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AnalyzersController do

  # This should return the minimal set of attributes required to create a valid
  # Analyzer. As you add validations to Analyzer, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all analyzers as @analyzers" do
      analyzer = Analyzer.create! valid_attributes
      get :index
      assigns(:analyzers).should eq([analyzer])
    end
  end

  describe "GET show" do
    it "assigns the requested analyzer as @analyzer" do
      analyzer = Analyzer.create! valid_attributes
      get :show, :id => analyzer.id
      assigns(:analyzer).should eq(analyzer)
    end
  end

  describe "GET new" do
    it "assigns a new analyzer as @analyzer" do
      get :new
      assigns(:analyzer).should be_a_new(Analyzer)
    end
  end

  describe "GET edit" do
    it "assigns the requested analyzer as @analyzer" do
      analyzer = Analyzer.create! valid_attributes
      get :edit, :id => analyzer.id
      assigns(:analyzer).should eq(analyzer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Analyzer" do
        expect {
          post :create, :analyzer => valid_attributes
        }.to change(Analyzer, :count).by(1)
      end

      it "assigns a newly created analyzer as @analyzer" do
        post :create, :analyzer => valid_attributes
        assigns(:analyzer).should be_a(Analyzer)
        assigns(:analyzer).should be_persisted
      end

      it "redirects to the created analyzer" do
        post :create, :analyzer => valid_attributes
        response.should redirect_to(Analyzer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved analyzer as @analyzer" do
        # Trigger the behavior that occurs when invalid params are submitted
        Analyzer.any_instance.stub(:save).and_return(false)
        post :create, :analyzer => {}
        assigns(:analyzer).should be_a_new(Analyzer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Analyzer.any_instance.stub(:save).and_return(false)
        post :create, :analyzer => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested analyzer" do
        analyzer = Analyzer.create! valid_attributes
        # Assuming there are no other analyzers in the database, this
        # specifies that the Analyzer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Analyzer.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => analyzer.id, :analyzer => {'these' => 'params'}
      end

      it "assigns the requested analyzer as @analyzer" do
        analyzer = Analyzer.create! valid_attributes
        put :update, :id => analyzer.id, :analyzer => valid_attributes
        assigns(:analyzer).should eq(analyzer)
      end

      it "redirects to the analyzer" do
        analyzer = Analyzer.create! valid_attributes
        put :update, :id => analyzer.id, :analyzer => valid_attributes
        response.should redirect_to(analyzer)
      end
    end

    describe "with invalid params" do
      it "assigns the analyzer as @analyzer" do
        analyzer = Analyzer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Analyzer.any_instance.stub(:save).and_return(false)
        put :update, :id => analyzer.id, :analyzer => {}
        assigns(:analyzer).should eq(analyzer)
      end

      it "re-renders the 'edit' template" do
        analyzer = Analyzer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Analyzer.any_instance.stub(:save).and_return(false)
        put :update, :id => analyzer.id, :analyzer => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested analyzer" do
      analyzer = Analyzer.create! valid_attributes
      expect {
        delete :destroy, :id => analyzer.id
      }.to change(Analyzer, :count).by(-1)
    end

    it "redirects to the analyzers list" do
      analyzer = Analyzer.create! valid_attributes
      delete :destroy, :id => analyzer.id
      response.should redirect_to(analyzers_url)
    end
  end

end
