require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CtwsController do

  # This should return the minimal set of attributes required to create a valid
  # Ctw. As you add validations to Ctw, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all ctws as @ctws" do
      ctw = Ctw.create! valid_attributes
      get :index
      assigns(:ctws).should eq([ctw])
    end
  end

  describe "GET show" do
    it "assigns the requested ctw as @ctw" do
      ctw = Ctw.create! valid_attributes
      get :show, :id => ctw.id
      assigns(:ctw).should eq(ctw)
    end
  end

  describe "GET new" do
    it "assigns a new ctw as @ctw" do
      get :new
      assigns(:ctw).should be_a_new(Ctw)
    end
  end

  describe "GET edit" do
    it "assigns the requested ctw as @ctw" do
      ctw = Ctw.create! valid_attributes
      get :edit, :id => ctw.id
      assigns(:ctw).should eq(ctw)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Ctw" do
        expect {
          post :create, :ctw => valid_attributes
        }.to change(Ctw, :count).by(1)
      end

      it "assigns a newly created ctw as @ctw" do
        post :create, :ctw => valid_attributes
        assigns(:ctw).should be_a(Ctw)
        assigns(:ctw).should be_persisted
      end

      it "redirects to the created ctw" do
        post :create, :ctw => valid_attributes
        response.should redirect_to(Ctw.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ctw as @ctw" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ctw.any_instance.stub(:save).and_return(false)
        post :create, :ctw => {}
        assigns(:ctw).should be_a_new(Ctw)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ctw.any_instance.stub(:save).and_return(false)
        post :create, :ctw => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ctw" do
        ctw = Ctw.create! valid_attributes
        # Assuming there are no other ctws in the database, this
        # specifies that the Ctw created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Ctw.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => ctw.id, :ctw => {'these' => 'params'}
      end

      it "assigns the requested ctw as @ctw" do
        ctw = Ctw.create! valid_attributes
        put :update, :id => ctw.id, :ctw => valid_attributes
        assigns(:ctw).should eq(ctw)
      end

      it "redirects to the ctw" do
        ctw = Ctw.create! valid_attributes
        put :update, :id => ctw.id, :ctw => valid_attributes
        response.should redirect_to(ctw)
      end
    end

    describe "with invalid params" do
      it "assigns the ctw as @ctw" do
        ctw = Ctw.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ctw.any_instance.stub(:save).and_return(false)
        put :update, :id => ctw.id, :ctw => {}
        assigns(:ctw).should eq(ctw)
      end

      it "re-renders the 'edit' template" do
        ctw = Ctw.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ctw.any_instance.stub(:save).and_return(false)
        put :update, :id => ctw.id, :ctw => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ctw" do
      ctw = Ctw.create! valid_attributes
      expect {
        delete :destroy, :id => ctw.id
      }.to change(Ctw, :count).by(-1)
    end

    it "redirects to the ctws list" do
      ctw = Ctw.create! valid_attributes
      delete :destroy, :id => ctw.id
      response.should redirect_to(ctws_url)
    end
  end

end
